base_images:
  ansible:
    name: "4.15"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.15"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.15"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.15"
    namespace: ocp
    tag: upi-installer
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.15"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-debug
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: gcp-qe
    env:
      BOOTSTRAP_NODE_TYPE: t2a-standard-4
      COMPUTE_NODE_TYPE: t2a-standard-2
      CONTROL_PLANE_NODE_TYPE: t2a-standard-4
      OCP_ARCH: arm64
    workflow: cucushift-installer-rehearse-gcp-upi-private-xpn-ingress-glb
- as: installer-rehearse-aws
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      RHEL_VM_TYPE: m5.xlarge
      RHEL_WORKER_COUNT_PER_ZONE: "3"
    workflow: cucushift-installer-rehearse-aws-ipi-proxy-workers-rhel8
- as: installer-rehearse-azure
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
    workflow: cucushift-installer-rehearse-azure-ipi-disk-encryption-set-day2
- as: installer-rehearse-azure-aro
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: azure-qe
    env:
      ARO_CLUSTER_VERSION: 4.15.27
      ARO_FIPS: "true"
    workflow: cucushift-installer-rehearse-azure-aro-byonsg
- as: installer-rehearse-ibmcloud
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: ibmcloud-qe
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-proxy
- as: installer-rehearse-gcp
  cron: '@yearly'
  steps:
    allow_skip_on_success: true
    cluster_profile: gcp-qe
    dependency_overrides:
      OO_INDEX: quay.io/openshift-qe-optional-operators/aosqe-index:v4.15
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    workflow: cucushift-installer-rehearse-gcp-ipi-user-labels-tags-filestore-csi
zz_generated_metadata:
  branch: main
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.15
